FROM alpine:3.21

RUN apk update && apk upgrade && apk add mariadb mariadb-client

RUN mariadb-install-db --skip-test-db --auth-root-authentication-method=normal --datadir=/var/lib/mysql

COPY conf/mariadb.conf /etc/mysql/my.cnf
COPY tools/mariadb.sh /usr/local/bin/mariadb.sh
RUN chmod +x /usr/local/bin/mariadb.sh

RUN mkdir -p /run/mysqld


EXPOSE 3306

ENTRYPOINT ["/bin/sh","/usr/local/bin/mariadb.sh"]
